import { Archive, Download, Eye, Receipt } from "lucide-react";
import { formatBDT, formatDisplayDate } from "../utils/moneyFormatter";

const STATUS_STYLES = {
  paid: "bg-emerald-50 text-emerald-700",
  partially_paid: "bg-amber-50 text-amber-700",
  unpaid: "bg-red-50 text-red-700",
};
const STATUS_LABELS = { paid: "PAID", partially_paid: "PARTIALLY PAID", unpaid: "UNPAID" };

const BOOKING_STATUS_STYLES = {
  confirmed: "bg-emerald-50 text-emerald-700",
  not_confirmed: "bg-slate-100 text-slate-500",
};
const BOOKING_STATUS_LABELS = { confirmed: "CONFIRMED", not_confirmed: "NOT CONFIRM" };

// Every generated money receipt, newest first — financial records, so
// Archive never deletes anything (see moneyReceiptController.js).
export default function MoneyReceiptHistoryTable({ receipts, onPreview, onDownload, onArchive, busyReceiptId }) {
  if (receipts.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center gap-2 rounded-2xl border border-dashed border-mme-pink/60 bg-white py-14 text-mme-purple/35">
        <Receipt size={28} />
        <p className="text-sm font-bold">No money receipts generated yet.</p>
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-2xl border border-mme-pink/60 bg-white shadow-sm">
      <div className="overflow-x-auto">
        <table className="w-full min-w-220 text-left text-sm">
          <thead className="border-b border-mme-pink/50 bg-mme-blush/20 text-[11px] font-black uppercase tracking-wide text-slate-500">
            <tr>
              <th className="px-4 py-3">Receipt No</th>
              <th className="px-4 py-3">Date</th>
              <th className="px-4 py-3">Client</th>
              <th className="px-4 py-3">Event</th>
              <th className="px-4 py-3">Booking</th>
              <th className="px-4 py-3">Total</th>
              <th className="px-4 py-3">Advance</th>
              <th className="px-4 py-3">Due</th>
              <th className="px-4 py-3">Payment Status</th>
              <th className="px-4 py-3">Generated By</th>
              <th className="px-4 py-3">Status</th>
              <th className="px-4 py-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {receipts.map((receipt) => {
              const isBusy = busyReceiptId === receipt.id;
              return (
                <tr key={receipt.id} className="transition-colors hover:bg-mme-blush/10">
                  <td className="px-4 py-3 font-bold text-slate-700">{receipt.receiptNo || "—"}</td>
                  <td className="px-4 py-3 text-slate-600">{formatDisplayDate(receipt.receiptDate)}</td>
                  <td className="px-4 py-3 font-semibold text-slate-800">{receipt.clientName}</td>
                  <td className="px-4 py-3 text-slate-600">{receipt.eventName || "—"}</td>
                  <td className="px-4 py-3">
                    <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${BOOKING_STATUS_STYLES[receipt.bookingStatus]}`}>
                      {BOOKING_STATUS_LABELS[receipt.bookingStatus]}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-slate-600">{formatBDT(receipt.totalPayment)}</td>
                  <td className="px-4 py-3 text-slate-600">{formatBDT(receipt.advancePayment)}</td>
                  <td className="px-4 py-3 font-bold text-slate-700">{formatBDT(receipt.duePayment)}</td>
                  <td className="px-4 py-3">
                    <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${STATUS_STYLES[receipt.paymentStatus]}`}>
                      {STATUS_LABELS[receipt.paymentStatus]}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-slate-600">{receipt.createdByName || "—"}</td>
                  <td className="px-4 py-3">
                    <span
                      className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${
                        receipt.status === "archived" ? "bg-slate-100 text-slate-500" : "bg-mme-purple/10 text-mme-purple"
                      }`}
                    >
                      {receipt.status}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center justify-end gap-1.5">
                      <button
                        type="button"
                        onClick={() => onPreview(receipt.id)}
                        disabled={isBusy}
                        title="Preview"
                        className="flex h-8 w-8 items-center justify-center rounded-lg text-mme-purple/50 transition-colors hover:bg-mme-blush/40 hover:text-mme-purple disabled:opacity-40"
                      >
                        <Eye size={16} />
                      </button>
                      <button
                        type="button"
                        onClick={() => onDownload(receipt.id)}
                        disabled={isBusy}
                        title="Download"
                        className="flex h-8 w-8 items-center justify-center rounded-lg text-mme-purple/50 transition-colors hover:bg-mme-blush/40 hover:text-mme-purple disabled:opacity-40"
                      >
                        <Download size={16} />
                      </button>
                      {receipt.status !== "archived" && (
                        <button
                          type="button"
                          onClick={() => onArchive(receipt.id)}
                          disabled={isBusy}
                          title="Archive"
                          className="flex h-8 w-8 items-center justify-center rounded-lg text-mme-purple/50 transition-colors hover:bg-mme-blush/40 hover:text-mme-purple disabled:opacity-40"
                        >
                          <Archive size={16} />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
